CREATE TABLE IF NOT EXISTS coffee_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(255),
    size VARCHAR(255),
    price VARCHAR(255),
    card_name VARCHAR(255),
    card_number VARCHAR(32),
    order_time TIMESTAMP
);
